keystore:
	-rm src/main/resources/keystore/gruppe3.p12
	keytool -genkeypair -dname "cn=, ou=, o=, c=NO" -alias gruppe3 -keypass password -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore src/main/resources/keystore/gruppe3.p12 -storepass password -validity 3650